server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/cinema-control-api-db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_schema: auth
    show-sql: true


jwt:
  secret: super-secret-key-change-me
  access-token-expiration-minutes: 60
  refresh-token-expiration-days: 7

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs